apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-app
  namespace: argocd
spec:
  replicas: 4
  selector:
    matchLabels:
      app: will-app
  template:
    metadata:
      labels:
        app: will-app
    spec:
      containers:
      - name: wapp
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: will-app-service
  namespace: argocd
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: will-app
  type: ClusterIP
